import os, sqlite3, secrets, smtplib
from functools import wraps
from pathlib import Path
from datetime import date
from flask import Flask, render_template, render_template_string, request, redirect, url_for, session, jsonify, abort
from werkzeug.security import generate_password_hash, check_password_hash
from itsdangerous import URLSafeTimedSerializer, BadSignature, SignatureExpired
from email.message import EmailMessage
from dotenv import load_dotenv
load_dotenv()
from discord_oauth import discord_login, discord_callback

app = Flask(__name__)
app.secret_key = os.getenv("PSL_SECRET_KEY", "change-this-secret-key")
DB = Path("psl.db")
ADMIN_USER = os.getenv("PSL_ADMIN_USER", "admin")
ADMIN_PASSWORD = os.getenv("PSL_ADMIN_PASSWORD", "changeme")
ADMIN_USER_2 = os.getenv("PSL_ADMIN_USER_2", "")
ADMIN_PASSWORD_2 = os.getenv("PSL_ADMIN_PASSWORD_2", "")
ADMIN_ACCOUNTS = [
    (ADMIN_USER, ADMIN_PASSWORD),
    (ADMIN_USER_2, ADMIN_PASSWORD_2),
]
API_KEY = os.getenv("PSL_API_KEY", "change-api-key")

def db():
    database_url = os.getenv("DATABASE_URL")
    if database_url:
        import psycopg
        from psycopg.rows import dict_row

        conn = psycopg.connect(database_url, row_factory=dict_row)

        class PGCompat:
            def __init__(self, connection):
                self.connection = connection

            def execute(self, sql, params=None):
                sql = sql.replace("?", "%s")
                return self.connection.execute(sql, params or ())

            def commit(self):
                self.connection.commit()

            def rollback(self):
                self.connection.rollback()

            def close(self):
                self.connection.close()

        return PGCompat(conn)

    c = sqlite3.connect(DB)
    c.row_factory = sqlite3.Row
    c.execute("PRAGMA foreign_keys = ON")
    return c

def init_db():
    c = db()
    if os.getenv("DATABASE_URL"):
        c.execute("""
        CREATE TABLE IF NOT EXISTS teams (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name TEXT NOT NULL UNIQUE,
          manager TEXT DEFAULT '',
          logo TEXT DEFAULT '',
          discord_id TEXT
        )
        """)
        c.execute("""
        CREATE TABLE IF NOT EXISTS players (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name TEXT NOT NULL,
          position TEXT DEFAULT '',
          team_id BIGINT,
          appearances INTEGER DEFAULT 0,
          goals INTEGER DEFAULT 0,
          assists INTEGER DEFAULT 0,
          discord_id TEXT,
          FOREIGN KEY(team_id) REFERENCES teams(id) ON DELETE SET NULL
        )
        """)
        c.execute("""
        CREATE TABLE IF NOT EXISTS users (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          username TEXT NOT NULL UNIQUE,
          email TEXT NOT NULL UNIQUE,
          password_hash TEXT NOT NULL,
          team_id BIGINT,
          player_id BIGINT,
          discord_id TEXT UNIQUE,
          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
          FOREIGN KEY(team_id) REFERENCES teams(id) ON DELETE SET NULL,
          FOREIGN KEY(player_id) REFERENCES players(id) ON DELETE SET NULL
        )
        """)
        c.execute("""
        CREATE TABLE IF NOT EXISTS fixtures (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          home_id BIGINT NOT NULL,
          away_id BIGINT NOT NULL,
          scheduled TEXT DEFAULT '',
          status TEXT DEFAULT 'scheduled',
          home_score INTEGER,
          away_score INTEGER,
          round_no INTEGER DEFAULT NULL,
          FOREIGN KEY(home_id) REFERENCES teams(id),
          FOREIGN KEY(away_id) REFERENCES teams(id)
        )
        """)
        c.execute("""
        CREATE TABLE IF NOT EXISTS transfers (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          player_id BIGINT NOT NULL,
          from_team TEXT DEFAULT 'Free Agent',
          to_team TEXT NOT NULL,
          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
          FOREIGN KEY(player_id) REFERENCES players(id)
        )
        """)
        c.execute("""
        CREATE TABLE IF NOT EXISTS totw (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          week TEXT NOT NULL,
          player_id BIGINT NOT NULL,
          position TEXT DEFAULT '',
          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
          FOREIGN KEY(player_id) REFERENCES players(id)
        )
        """)
        c.execute("ALTER TABLE teams ADD COLUMN IF NOT EXISTS discord_id TEXT")
        c.execute("ALTER TABLE players ADD COLUMN IF NOT EXISTS discord_id TEXT")
        c.execute("ALTER TABLE fixtures ADD COLUMN IF NOT EXISTS round_no INTEGER DEFAULT NULL")
    else:
        c.executescript("""
        CREATE TABLE IF NOT EXISTS teams (
          id INTEGER PRIMARY KEY AUTOINCREMENT,
          name TEXT NOT NULL UNIQUE, manager TEXT DEFAULT '', logo TEXT DEFAULT '', discord_id TEXT
        );
        CREATE TABLE IF NOT EXISTS players (
          id INTEGER PRIMARY KEY AUTOINCREMENT,
          name TEXT NOT NULL, position TEXT DEFAULT '', team_id INTEGER,
          appearances INTEGER DEFAULT 0, goals INTEGER DEFAULT 0, assists INTEGER DEFAULT 0,
          discord_id TEXT,
          FOREIGN KEY(team_id) REFERENCES teams(id) ON DELETE SET NULL
        );
        CREATE TABLE IF NOT EXISTS fixtures (
          id INTEGER PRIMARY KEY AUTOINCREMENT,
          home_id INTEGER NOT NULL, away_id INTEGER NOT NULL,
          scheduled TEXT DEFAULT '', status TEXT DEFAULT 'scheduled',
          home_score INTEGER, away_score INTEGER,
          round_no INTEGER DEFAULT NULL,
          FOREIGN KEY(home_id) REFERENCES teams(id), FOREIGN KEY(away_id) REFERENCES teams(id)
        );
        CREATE TABLE IF NOT EXISTS transfers (
          id INTEGER PRIMARY KEY AUTOINCREMENT,
          player_id INTEGER NOT NULL, from_team TEXT DEFAULT 'Free Agent',
          to_team TEXT NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
          FOREIGN KEY(player_id) REFERENCES players(id)
        );
        CREATE TABLE IF NOT EXISTS totw (
          id INTEGER PRIMARY KEY AUTOINCREMENT, week TEXT NOT NULL,
          player_id INTEGER NOT NULL, position TEXT DEFAULT '', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
          FOREIGN KEY(player_id) REFERENCES players(id)
        );
        """)
        c.execute("""
        CREATE TABLE IF NOT EXISTS users (
          id INTEGER PRIMARY KEY AUTOINCREMENT,
          username TEXT NOT NULL UNIQUE,
          email TEXT NOT NULL UNIQUE,
          password_hash TEXT NOT NULL,
          team_id INTEGER,
          player_id INTEGER,
          discord_id TEXT UNIQUE,
          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
          FOREIGN KEY(team_id) REFERENCES teams(id) ON DELETE SET NULL,
          FOREIGN KEY(player_id) REFERENCES players(id) ON DELETE SET NULL
        )
        """)
        cols = {r[1] for r in c.execute("PRAGMA table_info(fixtures)").fetchall()}
        if "round_no" not in cols:
            c.execute("ALTER TABLE fixtures ADD COLUMN round_no INTEGER DEFAULT NULL")
        player_cols = {r[1] for r in c.execute("PRAGMA table_info(players)").fetchall()}
        if "discord_id" not in player_cols:
            c.execute("ALTER TABLE players ADD COLUMN discord_id TEXT")
        team_cols = {r[1] for r in c.execute("PRAGMA table_info(teams)").fetchall()}
        if "discord_id" not in team_cols:
            c.execute("ALTER TABLE teams ADD COLUMN discord_id TEXT")

    c.commit()
    c.close()

def admin_required(fn):
    @wraps(fn)
    def wrapper(*a, **kw):
        if not session.get("admin"):
            return redirect(url_for("login", next=request.path))
        return fn(*a, **kw)
    return wrapper

def standings():
    c = db()
    teams = c.execute("SELECT * FROM teams ORDER BY name").fetchall()
    out = {t["id"]: dict(team=t["name"], played=0,wins=0,draws=0,losses=0,gf=0,ga=0,gd=0,points=0) for t in teams}
    for r in c.execute("SELECT * FROM fixtures WHERE status='played'").fetchall():
        h,a=out[r["home_id"]],out[r["away_id"]]
        hs,as_=r["home_score"],r["away_score"]
        h["played"]+=1;a["played"]+=1;h["gf"]+=hs;h["ga"]+=as_;a["gf"]+=as_;a["ga"]+=hs
        if hs>as_: h["wins"]+=1;h["points"]+=3;a["losses"]+=1
        elif hs<as_: a["wins"]+=1;a["points"]+=3;h["losses"]+=1
        else: h["draws"]+=1;a["draws"]+=1;h["points"]+=1;a["points"]+=1
    for x in out.values(): x["gd"]=x["gf"]-x["ga"]
    c.close()
    return sorted(out.values(), key=lambda x:(-x["points"],-x["gd"],-x["gf"],x["team"]))

def account_serializer():
    return URLSafeTimedSerializer(app.secret_key, salt="psl-password-reset")


def current_user():
    user_id = session.get("user_id")
    if not user_id:
        return None
    c = db()
    user = c.execute("""SELECT u.*, COALESCE(t.name,'Free Agent') team_name,
                       p.name player_name, p.position, p.appearances, p.goals, p.assists
                       FROM users u
                       LEFT JOIN teams t ON t.id=u.team_id
                       LEFT JOIN players p ON p.id=u.player_id
                       WHERE u.id=?""", (user_id,)).fetchone()
    c.close()
    return user


def send_password_reset_email(email, reset_url):
    """Send a password-reset email and log failures without exposing credentials."""
    host = (os.getenv("PSL_SMTP_HOST") or "").strip()
    username = (os.getenv("PSL_SMTP_USER") or "").strip()
    password = os.getenv("PSL_SMTP_PASSWORD") or ""
    sender = (os.getenv("PSL_SMTP_FROM") or username).strip()
    try:
        port = int(os.getenv("PSL_SMTP_PORT", "587"))
    except (TypeError, ValueError):
        app.logger.error("Password reset SMTP configuration invalid: PSL_SMTP_PORT must be a number")
        return False, "Password reset email is not configured correctly. Please contact the PSL administrator."

    missing = []
    if not host:
        missing.append("PSL_SMTP_HOST")
    if not username:
        missing.append("PSL_SMTP_USER")
    if not password:
        missing.append("PSL_SMTP_PASSWORD")
    if not sender:
        missing.append("PSL_SMTP_FROM")
    if missing:
        app.logger.error("Password reset SMTP configuration incomplete; missing: %s", ", ".join(missing))
        return False, "Password reset email is not configured correctly. Please contact the PSL administrator."

    msg = EmailMessage()
    msg["Subject"] = "PSL password reset"
    msg["From"] = sender
    msg["To"] = email
    msg.set_content(
        "Someone requested a password reset for your PSL account.\n\n"
        f"Reset your password here:\n{reset_url}\n\n"
        "This link expires after 30 minutes. If you did not request this, you can ignore this email."
    )
    try:
        with smtplib.SMTP(host, port, timeout=20) as smtp:
            smtp.ehlo()
            smtp.starttls()
            smtp.ehlo()
            smtp.login(username, password)
            refused = smtp.send_message(msg)
        if refused:
            app.logger.error("Password reset email was refused for one or more recipients")
            return False, "We could not send the reset email right now. Please try again later."
        app.logger.info("Password reset email accepted by SMTP server")
        return True, "Password reset instructions have been emailed to you. Check your inbox and spam folder."
    except Exception:
        app.logger.exception("Password reset email failed during SMTP connection, authentication, or delivery")
        return False, "We could not send the reset email right now. Please try again later."

@app.context_processor
def globals_():
    return {
        "logged_in": bool(session.get("admin")),
        "discord_logged_in": bool(session.get("discord_id")),
        "user_logged_in": bool(session.get("user_id")),
        "current_user": current_user(),
    }

@app.route("/")
def home():
    c=db()
    recent=c.execute("""SELECT f.*,h.name home,a.name away FROM fixtures f
      JOIN teams h ON h.id=f.home_id JOIN teams a ON a.id=f.away_id
      WHERE f.status='played' ORDER BY f.id DESC LIMIT 5""").fetchall()
    upcoming=c.execute("""SELECT f.*,h.name home,a.name away FROM fixtures f
      JOIN teams h ON h.id=f.home_id JOIN teams a ON a.id=f.away_id
      WHERE f.status='scheduled' ORDER BY f.scheduled,f.id LIMIT 5""").fetchall()
    top=c.execute("""SELECT p.*,COALESCE(t.name,'Free Agent') team FROM players p
      LEFT JOIN teams t ON t.id=p.team_id ORDER BY p.goals DESC,p.assists DESC LIMIT 5""").fetchall()
    counts=[c.execute("SELECT COUNT(*) n FROM teams").fetchone()["n"],
            c.execute("SELECT COUNT(*) n FROM players").fetchone()["n"],
            c.execute("SELECT COUNT(*) n FROM fixtures WHERE status='played'").fetchone()["n"]]
    c.close()
    return render_template("home.html",table=standings()[:6],recent=recent,upcoming=upcoming,top=top,counts=counts)

@app.route("/table")
def table(): return render_template("table.html", table=standings())

@app.route("/teams")
def teams():
    c=db(); rows=c.execute("SELECT * FROM teams ORDER BY name").fetchall(); c.close()
    return render_template("teams.html",teams=rows)

@app.route("/team/<int:team_id>")
def team(team_id):
    c=db(); t=c.execute("SELECT * FROM teams WHERE id=?",(team_id,)).fetchone()
    if not t: abort(404)
    players=c.execute("SELECT * FROM players WHERE team_id=? ORDER BY name",(team_id,)).fetchall()
    fixtures=c.execute("""SELECT f.*,h.name home,a.name away FROM fixtures f
      JOIN teams h ON h.id=f.home_id JOIN teams a ON a.id=f.away_id
      WHERE h.id=? OR a.id=? ORDER BY f.id DESC LIMIT 20""",(team_id,team_id)).fetchall()
    c.close(); return render_template("team.html",team=t,players=players,fixtures=fixtures)

@app.route("/players")
def players():
    c=db(); rows=c.execute("""SELECT p.*,COALESCE(t.name,'Free Agent') team FROM players p
      LEFT JOIN teams t ON t.id=p.team_id ORDER BY p.goals DESC,p.assists DESC,p.name""").fetchall(); c.close()
    return render_template("players.html",players=rows)

@app.route("/player/<int:player_id>")
def player(player_id):
    c=db(); p=c.execute("""SELECT p.*,COALESCE(t.name,'Free Agent') team FROM players p
      LEFT JOIN teams t ON t.id=p.team_id WHERE p.id=?""",(player_id,)).fetchone()
    if not p: abort(404)
    transfers=c.execute("SELECT * FROM transfers WHERE player_id=? ORDER BY id DESC",(player_id,)).fetchall()
    c.close(); return render_template("player.html",player=p,transfers=transfers)

@app.route("/fixtures", methods=["GET","POST"])
def fixtures():
    c=db()
    if request.method == "POST":
        if not session.get("admin"):
            return redirect(url_for("login", next=url_for("fixtures")))
        fixture_id = request.form.get("fixture_id")
        home_score = request.form.get("home_score")
        away_score = request.form.get("away_score")
        if fixture_id and home_score is not None and away_score is not None:
            try:
                hs, as_ = int(home_score), int(away_score)
                if hs >= 0 and as_ >= 0:
                    c.execute("UPDATE fixtures SET status='played',home_score=?,away_score=? WHERE id=?", (hs, as_, int(fixture_id)))
                    c.commit()
            except ValueError:
                pass
        c.close()
        return redirect(url_for("fixtures"))
    rows=c.execute("""SELECT f.*,h.name home,a.name away FROM fixtures f
      JOIN teams h ON h.id=f.home_id JOIN teams a ON a.id=f.away_id
      ORDER BY COALESCE(f.round_no, 999999), f.id""").fetchall(); c.close()
    return render_template("fixtures.html",fixtures=rows)

@app.route("/transfers")
def transfers():
    c=db(); rows=c.execute("""SELECT tr.*,p.name player FROM transfers tr JOIN players p ON p.id=tr.player_id
      ORDER BY tr.id DESC""").fetchall(); c.close(); return render_template("transfers.html",transfers=rows)

@app.route("/totw")
def totw():
    c=db(); rows=c.execute("""SELECT t.week,p.id player_id,p.name,p.position,COALESCE(te.name,'Free Agent') team
      FROM totw t JOIN players p ON p.id=t.player_id LEFT JOIN teams te ON te.id=p.team_id
      ORDER BY t.id DESC""").fetchall(); c.close(); return render_template("totw.html",rows=rows)

@app.route("/auth/discord")
def auth_discord(): return discord_login()

@app.route("/auth/discord/callback")
def auth_discord_callback():
    response = discord_callback()
    # If a normal website account is already logged in, attach this Discord account to it.
    if session.get("user_id") and session.get("discord_id"):
        c = db()
        existing = c.execute("SELECT id FROM users WHERE discord_id=? AND id<>?", (session["discord_id"], session["user_id"])).fetchone()
        if not existing:
            c.execute("UPDATE users SET discord_id=? WHERE id=?", (session["discord_id"], session["user_id"]))
            c.commit()
        c.close()
        return redirect(url_for("account_dashboard"))
    return response


def manager_required(fn):
    @wraps(fn)
    def wrapper(*a, **kw):
        discord_id = session.get("discord_id")
        if not discord_id:
            return redirect(url_for("login", next=request.path))
        c = db()
        team = c.execute("SELECT * FROM teams WHERE discord_id=?", (discord_id,)).fetchone()
        c.close()
        if not team:
            return "Your Discord account is not linked to a PSL team yet. Ask the admin to link your Discord ID.", 403
        return fn(team, *a, **kw)
    return wrapper


@app.route("/manager", methods=["GET", "POST"])
@manager_required
def manager_dashboard(team):
    c = db()

    if request.method == "POST":
        action = request.form.get("action")
        if action == "sign_player":
            player_id = request.form.get("player_id")
            if player_id:
                player = c.execute(
                    "SELECT * FROM players WHERE id=?",
                    (player_id,)
                ).fetchone()

                if not player:
                    c.close()
                    return "Player not found.", 404

                if player["team_id"] is not None:
                    c.close()
                    return "That player is already signed.", 400

                c.execute(
                    "INSERT INTO transfers(player_id,from_team,to_team) VALUES(?,?,?)",
                    (player["id"], "Free Agent", team["name"])
                )
                c.execute(
                    "UPDATE players SET team_id=? WHERE id=?",
                    (team["id"], player["id"])
                )
                c.commit()

    my_players = c.execute(
        "SELECT * FROM players WHERE team_id=? ORDER BY position,name",
        (team["id"],)
    ).fetchall()

    free_agents = c.execute(
        "SELECT * FROM players WHERE team_id IS NULL ORDER BY position,name"
    ).fetchall()

    c.close()

    return render_template(
        "manager.html",
        team=team,
        players=my_players,
        free_agents=free_agents,
        discord_id=session.get("discord_id"),
    )


def player_required(fn):
    @wraps(fn)
    def wrapper(*a, **kw):
        discord_id = session.get("discord_id")
        if not discord_id:
            return redirect(url_for("login", next=request.path))

        c = db()
        player = c.execute(
            """SELECT p.*,COALESCE(t.name,'Free Agent') team, t.manager, t.logo
               FROM players p
               LEFT JOIN teams t ON t.id=p.team_id
               WHERE p.discord_id=?""",
            (discord_id,)
        ).fetchone()

        if not player:
            c.close()
            return "Your Discord account is not linked to a PSL player yet. Ask the admin to link your Discord ID.", 403

        return fn(player, *a, **kw)
    return wrapper


@app.route("/player-dashboard", methods=["GET"])
@player_required
def player_dashboard(player):
    c = db()
    transfers = c.execute(
        "SELECT * FROM transfers WHERE player_id=? ORDER BY id DESC",
        (player["id"],)
    ).fetchall()
    c.close()

    return render_template(
        "player_dashboard.html",
        player=player,
        transfers=transfers,
        discord_id=session.get("discord_id"),
    )



@app.route("/dashboard")
def dashboard():
    if session.get("admin"):
        return redirect(url_for("admin"))

    # Website account login.
    if session.get("user_id"):
        return redirect(url_for("account_dashboard"))

    # Existing Discord login remains optional.
    discord_id = session.get("discord_id")
    if not discord_id:
        return redirect(url_for("login", next=url_for("dashboard")))

    _auto_link_discord_account(discord_id) if "_auto_link_discord_account" in globals() else None

    c = db()
    user = c.execute("SELECT id FROM users WHERE discord_id=?", (discord_id,)).fetchone()
    if user:
        session["user_id"] = user["id"]
        c.close()
        return redirect(url_for("account_dashboard"))

    team = c.execute("SELECT id FROM teams WHERE discord_id=?", (discord_id,)).fetchone()
    if team:
        c.close()
        return redirect(url_for("manager_dashboard"))

    player = c.execute("SELECT id FROM players WHERE discord_id=?", (discord_id,)).fetchone()
    c.close()
    if player:
        return redirect(url_for("player_dashboard"))

    return redirect(url_for("claim")) if "claim" in app.view_functions else ("Your Discord account is not linked yet.", 403)


@app.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        username = request.form.get("username", "").strip()
        password = request.form.get("password", "")
        if any(username == user and password == secret for user, secret in ADMIN_ACCOUNTS if user and secret):
            session.clear()
            session["admin"] = True
            return redirect(request.args.get("next") or url_for("admin"))

        c = db()
        user = c.execute("SELECT * FROM users WHERE lower(username)=lower(?)", (username,)).fetchone()
        c.close()
        if user and check_password_hash(user["password_hash"], password):
            session.clear()
            session["user_id"] = user["id"]
            return redirect(request.args.get("next") or url_for("account_dashboard"))
        return render_template("login.html", error="Incorrect username or password.")
    return render_template("login.html")


@app.route("/register", methods=["GET", "POST"])
def register():
    if session.get("user_id"):
        return redirect(url_for("account_dashboard"))
    c = db()
    teams = c.execute("SELECT id,name FROM teams ORDER BY name").fetchall()
    error = None
    if request.method == "POST":
        username = request.form.get("username", "").strip()
        email = request.form.get("email", "").strip().lower()
        password = request.form.get("password", "")
        confirm = request.form.get("confirm_password", "")
        team_id = request.form.get("team_id") or None

        if len(username) < 3 or len(username) > 30:
            error = "Username must be between 3 and 30 characters."
        elif not email or "@" not in email:
            error = "Enter a valid email address."
        elif len(password) < 8:
            error = "Password must be at least 8 characters."
        elif password != confirm:
            error = "Passwords do not match."
        elif c.execute("SELECT 1 FROM users WHERE lower(username)=lower(?)", (username,)).fetchone():
            error = "That username is already registered."
        elif c.execute("SELECT 1 FROM users WHERE lower(email)=lower(?)", (email,)).fetchone():
            error = "That email is already registered."
        else:
            team = c.execute("SELECT id,name FROM teams WHERE id=?", (team_id,)).fetchone() if team_id else None
            c.execute("INSERT INTO users(username,email,password_hash,team_id) VALUES(?,?,?,?)",
                      (username, email, generate_password_hash(password), team["id"] if team else None))
            user_id = c.execute("SELECT id FROM users WHERE lower(username)=lower(?)", (username,)).fetchone()["id"]
            # Every website account gets a PSL player profile. Existing Discord-linked players can be linked later.
            c.execute("INSERT INTO players(name,position,team_id) VALUES(?,?,?)", (username, "", team["id"] if team else None))
            player_id = c.execute("SELECT id FROM players WHERE name=? ORDER BY id DESC LIMIT 1", (username,)).fetchone()["id"]
            c.execute("UPDATE users SET player_id=? WHERE id=?", (player_id, user_id))
            c.commit()
            c.close()
            session.clear()
            session["user_id"] = user_id
            return redirect(url_for("account_dashboard"))
    c.close()
    return render_template("register.html", teams=teams, error=error)


@app.route("/forgot-password", methods=["GET", "POST"])
def forgot_password():
    message = None
    error = None
    if request.method == "POST":
        email = request.form.get("email", "").strip().lower()
        c = db()
        user = c.execute("SELECT id,email FROM users WHERE lower(email)=lower(?)", (email,)).fetchone()
        c.close()
        # Keep the public response generic to avoid revealing whether an account exists,
        # but log the branch so administrators can diagnose why no email was sent.
        if user:
            app.logger.info("Password reset requested for a registered account")
            token = account_serializer().dumps({"user_id": user["id"], "email": user["email"]})
            reset_url = url_for("reset_password", token=token, _external=True)
            # Railway serves the public site over HTTPS; ensure reset links use HTTPS
            # even if the internal proxy connection is HTTP.
            if request.host.endswith(".up.railway.app") and reset_url.startswith("http://"):
                reset_url = "https://" + reset_url[len("http://"):]
            ok, msg = send_password_reset_email(user["email"], reset_url)
            if not ok:
                error = msg
            else:
                message = msg
        else:
            app.logger.warning("Password reset requested but no matching account was found; no email sent")
            message = "If an account exists for that email, reset instructions have been sent."
    return render_template("forgot_password.html", message=message, error=error)


@app.route("/reset-password/<token>", methods=["GET", "POST"])
def reset_password(token):
    try:
        data = account_serializer().loads(token, max_age=1800)
    except (BadSignature, SignatureExpired):
        return render_template("reset_password.html", error="This password reset link is invalid or has expired.", token=None)

    if request.method == "POST":
        password = request.form.get("password", "")
        confirm = request.form.get("confirm_password", "")
        if len(password) < 8:
            return render_template("reset_password.html", error="Password must be at least 8 characters.", token=token)
        if password != confirm:
            return render_template("reset_password.html", error="Passwords do not match.", token=token)
        c = db()
        c.execute("UPDATE users SET password_hash=? WHERE id=?", (generate_password_hash(password), data["user_id"]))
        c.commit(); c.close()
        return redirect(url_for("login", reset="1"))

    return render_template("reset_password.html", token=token)


@app.route("/account", methods=["GET", "POST"])
def account_dashboard():
    user_id = session.get("user_id")
    if not user_id:
        return redirect(url_for("login", next=url_for("account_dashboard")))

    c = db()
    if request.method == "POST":
        username = request.form.get("username", "").strip()
        email = request.form.get("email", "").strip().lower()
        team_id = request.form.get("team_id") or None
        current = c.execute("SELECT * FROM users WHERE id=?", (user_id,)).fetchone()
        if not current:
            c.close(); session.clear(); return redirect(url_for("login"))
        duplicate = c.execute("SELECT 1 FROM users WHERE id<>? AND lower(username)=lower(?)", (user_id, username)).fetchone()
        duplicate_email = c.execute("SELECT 1 FROM users WHERE id<>? AND lower(email)=lower(?)", (user_id, email)).fetchone()
        if not username or duplicate:
            error = "That username is unavailable."
        elif not email or "@" not in email or duplicate_email:
            error = "That email is unavailable."
        else:
            c.execute("UPDATE users SET username=?,email=?,team_id=? WHERE id=?", (username,email,team_id,user_id))
            if current["player_id"]:
                c.execute("UPDATE players SET name=?,team_id=? WHERE id=?", (username,team_id,current["player_id"]))
            c.commit()
            error = None
        teams = c.execute("SELECT id,name FROM teams ORDER BY name").fetchall()
        user = c.execute("""SELECT u.*,COALESCE(t.name,'Free Agent') team_name,
                            p.name player_name,p.position,p.appearances,p.goals,p.assists
                            FROM users u LEFT JOIN teams t ON t.id=u.team_id
                            LEFT JOIN players p ON p.id=u.player_id WHERE u.id=?""", (user_id,)).fetchone()
        c.close()
        return render_template("account.html", user=user, teams=teams, error=error)

    teams = c.execute("SELECT id,name FROM teams ORDER BY name").fetchall()
    user = c.execute("""SELECT u.*,COALESCE(t.name,'Free Agent') team_name,
                        p.name player_name,p.position,p.appearances,p.goals,p.assists
                        FROM users u LEFT JOIN teams t ON t.id=u.team_id
                        LEFT JOIN players p ON p.id=u.player_id WHERE u.id=?""", (user_id,)).fetchone()
    c.close()
    return render_template("account.html", user=user, teams=teams)


@app.route("/logout")
def logout():
    session.clear()
    return redirect(url_for("home"))

@app.route("/admin",methods=["GET","POST"])
@admin_required
def admin():
    c=db()
    if request.method=="POST":
        a=request.form["action"]
        if a=="team":
            if os.getenv("DATABASE_URL"):
                c.execute("INSERT INTO teams(name,manager,logo) VALUES(?,?,?) ON CONFLICT(name) DO NOTHING",
                          (request.form["name"].strip(),request.form.get("manager","").strip(),request.form.get("logo","").strip()))
            else:
                c.execute("INSERT OR IGNORE INTO teams(name,manager,logo) VALUES(?,?,?)",
                          (request.form["name"].strip(),request.form.get("manager","").strip(),request.form.get("logo","").strip()))
        elif a=="player":
            c.execute("INSERT INTO players(name,position,team_id) VALUES(?,?,?)",
                      (request.form["name"].strip(),request.form.get("position","").strip(),request.form.get("team_id") or None))
        elif a=="fixture":
            home_raw = request.form.get("home_id")
            away_raw = request.form.get("away_id")
            if home_raw and away_raw:
                home_id = int(home_raw)
                away_id = int(away_raw)
                if home_id != away_id:
                    exists = c.execute("SELECT 1 FROM fixtures WHERE home_id=? AND away_id=?", (home_id, away_id)).fetchone()
                    if not exists:
                        c.execute("INSERT INTO fixtures(home_id,away_id,scheduled) VALUES(?,?,?)",
                                  (home_id, away_id, request.form.get("scheduled", "")))
        elif a=="generate_fixtures":
            teams_for_schedule = c.execute("SELECT id, name FROM teams ORDER BY id").fetchall()
            if len(teams_for_schedule) == 10:
                # Circle method: 9 rounds, then repeat with home/away reversed = 90 games.
                ids = [t["id"] for t in teams_for_schedule]
                fixed = ids[0]
                rotating = ids[1:]
                rounds = []
                arr = rotating[:]
                for rnd in range(9):
                    current = [fixed] + arr
                    pairings = []
                    for i in range(5):
                        pairings.append((current[i], current[-1-i]))
                    rounds.append(pairings)
                    arr = [arr[-1]] + arr[:-1]

                created = 0
                for rnd, pairings in enumerate(rounds, start=1):
                    for home_id, away_id in pairings:
                        if not c.execute("SELECT 1 FROM fixtures WHERE home_id=? AND away_id=?", (home_id, away_id)).fetchone():
                            c.execute("INSERT INTO fixtures(home_id,away_id,scheduled,round_no) VALUES(?,?,?,?)",
                                      (home_id, away_id, f"Round {rnd}", rnd))
                            created += 1
                for rnd, pairings in enumerate(rounds, start=10):
                    original_rnd = rnd - 9
                    for home_id, away_id in pairings:
                        if not c.execute("SELECT 1 FROM fixtures WHERE home_id=? AND away_id=?", (away_id, home_id)).fetchone():
                            c.execute("INSERT INTO fixtures(home_id,away_id,scheduled,round_no) VALUES(?,?,?,?)",
                                      (away_id, home_id, f"Round {rnd}", rnd))
                            created += 1
        elif a=="result":
            c.execute("UPDATE fixtures SET status='played',home_score=?,away_score=? WHERE id=?",
                      (request.form["home_score"],request.form["away_score"],request.form["fixture_id"]))
        elif a=="transfer":
            p=c.execute("SELECT * FROM players WHERE id=?",(request.form["player_id"],)).fetchone()
            to_id=int(request.form["to_team"])
            to=c.execute("SELECT name FROM teams WHERE id=?",(to_id,)).fetchone()["name"]
            old = None
            if p["team_id"] is not None:
                old = c.execute("SELECT name FROM teams WHERE id=?",(p["team_id"],)).fetchone()
            old_name=old["name"] if old else "Free Agent"
            c.execute("INSERT INTO transfers(player_id,from_team,to_team) VALUES(?,?,?)",(p["id"],old_name,to))
            c.execute("UPDATE players SET team_id=? WHERE id=?",(to_id,p["id"]))
        elif a=="totw":
            c.execute("INSERT INTO totw(week,player_id,position) VALUES(?,?,?)",
                      (request.form["week"],request.form["player_id"],request.form.get("position","")))
        elif a=="link_discord":
            team_id = int(request.form["team_id"])
            discord_id = request.form["discord_id"].strip()
            c.execute("UPDATE teams SET discord_id=? WHERE id=?", (discord_id, team_id))
        elif a=="link_player_discord":
            player_id = int(request.form["player_id"])
            discord_id = request.form["discord_id"].strip()
            c.execute("UPDATE players SET discord_id=? WHERE id=?", (discord_id, player_id))
        c.commit()
    teams=c.execute("SELECT * FROM teams ORDER BY name").fetchall()
    players=c.execute("SELECT * FROM players ORDER BY name").fetchall()
    fixtures_=c.execute("""SELECT f.*,h.name home,a.name away FROM fixtures f
      JOIN teams h ON h.id=f.home_id JOIN teams a ON a.id=f.away_id ORDER BY f.id DESC""").fetchall()
    c.close(); return render_template("admin.html",teams=teams,players=players,fixtures=fixtures_)

# Discord bot -> website sync endpoint. Uses the configured PSL_API_KEY.
@app.post("/api/results")
def api_result():
    supplied_key = request.headers.get("X-PSL-API-KEY", "")
    configured_key = os.getenv("PSL_API_KEY", "")
    if not configured_key or configured_key in ("change-api-key", "replace-this-api-key"):
        return jsonify(error="PSL_API_KEY is not configured on the website"), 503
    if not secrets.compare_digest(supplied_key, configured_key):
        return jsonify(error="Unauthorized"), 401
    data = request.get_json(silent=True) or {}
    required = ("home", "away", "home_score", "away_score")
    if any(k not in data for k in required):
        return jsonify(error="Required fields: home, away, home_score, away_score"), 400
    try:
        home_name = str(data["home"]).strip()
        away_name = str(data["away"]).strip()
        home_score = int(data["home_score"])
        away_score = int(data["away_score"])
    except (TypeError, ValueError):
        return jsonify(error="Scores must be whole numbers"), 400
    if not home_name or not away_name or home_name.casefold() == away_name.casefold():
        return jsonify(error="Home and away must be different valid team names"), 400
    if home_score < 0 or away_score < 0:
        return jsonify(error="Scores cannot be negative"), 400
    c = db()
    h = c.execute("SELECT id FROM teams WHERE lower(name)=lower(?)", (home_name,)).fetchone()
    a = c.execute("SELECT id FROM teams WHERE lower(name)=lower(?)", (away_name,)).fetchone()
    if not h or not a:
        c.close()
        return jsonify(error="Team not found"), 404
    fixture = c.execute("SELECT id FROM fixtures WHERE status='scheduled' AND home_id=? AND away_id=? ORDER BY id LIMIT 1", (h["id"], a["id"])).fetchone()
    if fixture:
        fid = fixture["id"]
        c.execute("UPDATE fixtures SET status='played',home_score=?,away_score=? WHERE id=?", (home_score, away_score, fid))
    else:
        if os.getenv("DATABASE_URL"):
            fid = c.execute("INSERT INTO fixtures(home_id,away_id,status,home_score,away_score) VALUES(?,?,?,?,?) RETURNING id", (h["id"], a["id"], "played", home_score, away_score)).fetchone()["id"]
        else:
            c.execute("INSERT INTO fixtures(home_id,away_id,status,home_score,away_score) VALUES(?,?,?,?,?)", (h["id"], a["id"], "played", home_score, away_score))
            fid = c.execute("SELECT last_insert_rowid()").fetchone()[0]
    c.commit()
    c.close()
    return jsonify(ok=True, fixture_id=fid, home=home_name, away=away_name, score=f"{home_score}-{away_score}")

# ===== PSL_CONTRACTS_PATCH_V1 =====
def _contracts_table():
    c=db()
    if os.getenv("DATABASE_URL"):
        c.execute("""CREATE TABLE IF NOT EXISTS contracts (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          player_id BIGINT NOT NULL, team_id BIGINT NOT NULL,
          start_date DATE NOT NULL, end_date DATE NOT NULL,
          duration_months INTEGER NOT NULL DEFAULT 1, transfer_fee REAL DEFAULT 0,
          status TEXT NOT NULL DEFAULT 'active', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
          released_at DATE, FOREIGN KEY(player_id) REFERENCES players(id) ON DELETE CASCADE,
          FOREIGN KEY(team_id) REFERENCES teams(id) ON DELETE CASCADE)""")
    else:
        c.execute("""CREATE TABLE IF NOT EXISTS contracts (
          id INTEGER PRIMARY KEY AUTOINCREMENT,
          player_id INTEGER NOT NULL, team_id INTEGER NOT NULL,
          start_date TEXT NOT NULL, end_date TEXT NOT NULL,
          duration_months INTEGER NOT NULL DEFAULT 1, transfer_fee REAL DEFAULT 0,
          status TEXT NOT NULL DEFAULT 'active', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
          released_at TEXT, FOREIGN KEY(player_id) REFERENCES players(id) ON DELETE CASCADE,
          FOREIGN KEY(team_id) REFERENCES teams(id) ON DELETE CASCADE)""")
    c.commit(); c.close()

def _contract_add_months(d, months):
    import calendar
    y=d.year+(d.month-1+months)//12; m=(d.month-1+months)%12+1
    return date(y,m,min(d.day,calendar.monthrange(y,m)[1]))

init_db()

@app.route('/contracts')
def contracts_public():
    _contracts_table(); c=db()
    rows=c.execute("""SELECT co.*,p.name player,p.position,t.name team FROM contracts co
        JOIN players p ON p.id=co.player_id JOIN teams t ON t.id=co.team_id
        ORDER BY co.end_date ASC,p.name ASC""").fetchall(); c.close()
    return render_template_string("""
<!doctype html><html><head><meta charset='utf-8'><title>PSL Contracts</title>
<style>body{font-family:Arial;background:#111;color:#eee;padding:30px}.wrap{max-width:1100px;margin:auto}.card{background:#1b1b1b;border:1px solid #333;border-radius:14px;padding:18px;overflow:auto}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:11px;border-bottom:1px solid #333}th{color:#aaa}a{color:#7dd3fc}.active{color:#86efac}.expired{color:#fbbf24}.released{color:#f87171}</style></head>
<body><div class='wrap'><h1>PSL Contracts</h1><p>Player contracts, terms and status.</p><div class='card'><table><tr><th>Player</th><th>Team</th><th>Position</th><th>Start</th><th>End</th><th>Length</th><th>Fee</th><th>Status</th></tr>
{% for r in rows %}<tr><td>{{r.player}}</td><td>{{r.team}}</td><td>{{r.position}}</td><td>{{r.start_date}}</td><td>{{r.end_date}}</td><td>{{r.duration_months}}m</td><td>£{{'%.2f'|format(r.transfer_fee or 0)}}</td><td>{{r.status|upper}}</td></tr>{% else %}<tr><td colspan='8'>No contracts yet.</td></tr>{% endfor %}</table></div><p><a href='/'>Back to PSL</a></p></div></body></html>""",rows=rows)

@app.route('/manager/contracts',methods=['GET','POST'])
@manager_required
def manager_contracts(team):
    _contracts_table(); c=db(); message=None; error=None
    if request.method=='POST':
        action=request.form.get('action')
        try:
            if action=='sign_contract':
                player_id=int(request.form.get('player_id','0')); months=int(request.form.get('duration_months','1'))
                if months not in (1,3,6,12): raise ValueError('Contract length must be 1, 3, 6 or 12 months.')
                fee=float(request.form.get('transfer_fee','0') or 0)
                if fee<0: raise ValueError('Transfer fee cannot be negative.')
                p=c.execute('SELECT * FROM players WHERE id=?',(player_id,)).fetchone()
                if not p: raise ValueError('Player not found.')
                if p['team_id'] is not None: raise ValueError('That player is already signed to a team.')
                start=date.today(); end=_contract_add_months(start,months)
                c.execute("""INSERT INTO contracts(player_id,team_id,start_date,end_date,duration_months,transfer_fee,status)
                    VALUES(?,?,?,?,?,?,?)""",(player_id,team['id'],start.isoformat(),end.isoformat(),months,fee,'active'))
                c.execute('UPDATE players SET team_id=? WHERE id=?',(team['id'],player_id))
                c.execute("INSERT INTO transfers(player_id,from_team,to_team) VALUES(?,?,?)",(player_id,'Free Agent',team['name']))
                c.commit(); message=f"{p['name']} signed by {team['name']} until {end.isoformat()}."
            elif action=='release_contract':
                contract_id=int(request.form.get('contract_id','0'))
                r=c.execute("""SELECT co.*,p.name player FROM contracts co JOIN players p ON p.id=co.player_id
                    WHERE co.id=? AND co.team_id=? AND co.status='active'""",(contract_id,team['id'])).fetchone()
                if not r: raise ValueError('Active contract not found.')
                today=date.today().isoformat()
                c.execute("UPDATE contracts SET status='released',released_at=?,end_date=? WHERE id=?",(today,today,contract_id))
                c.execute('UPDATE players SET team_id=NULL WHERE id=? AND team_id=?',(r['player_id'],team['id']))
                c.execute("INSERT INTO transfers(player_id,from_team,to_team) VALUES(?,?,?)",(r['player_id'],team['name'],'Free Agent'))
                c.commit(); message=f"{r['player']} has been released and is now a Free Agent."
        except Exception as e:
            c.rollback(); error=str(e)
    mine=c.execute("""SELECT co.*,p.name player,p.position FROM contracts co JOIN players p ON p.id=co.player_id
        WHERE co.team_id=? ORDER BY co.end_date ASC""",(team['id'],)).fetchall()
    free_agents=c.execute('SELECT * FROM players WHERE team_id IS NULL ORDER BY position,name').fetchall(); c.close()
    return render_template_string("""
<!doctype html><html><head><meta charset='utf-8'><title>Team Contracts</title><style>
body{font-family:Arial;background:#111;color:#eee;padding:25px}.wrap{max-width:1100px;margin:auto}.card{background:#1b1b1b;border:1px solid #333;border-radius:14px;padding:20px;margin:15px 0}input,select{padding:10px;margin:5px;background:#222;color:#fff;border:1px solid #555;border-radius:7px}button{padding:10px 15px;background:#2563eb;color:#fff;border:0;border-radius:7px;cursor:pointer}.danger{background:#dc2626}.ok{background:#14532d;padding:12px;border-radius:8px}.err{background:#7f1d1d;padding:12px;border-radius:8px}table{width:100%;border-collapse:collapse}th,td{padding:10px;border-bottom:1px solid #333;text-align:left}a{color:#7dd3fc}</style></head>
<body><div class='wrap'><h1>{{team.name}} — Contracts</h1>{% if message %}<div class='ok'>{{message}}</div>{% endif %}{% if error %}<div class='err'>{{error}}</div>{% endif %}
<div class='card'><h2>Sign Free Agent</h2><form method='post'><input type='hidden' name='action' value='sign_contract'><select name='player_id' required>{% for p in free_agents %}<option value='{{p.id}}'>{{p.name}}{% if p.position %} — {{p.position}}{% endif %}</option>{% else %}<option>No free agents available</option>{% endfor %}</select><select name='duration_months'><option value='1'>1 month</option><option value='3'>3 months</option><option value='6'>6 months</option><option value='12'>12 months</option></select><input name='transfer_fee' type='number' step='0.01' min='0' value='0' placeholder='Transfer fee (£)'><button>Sign Player</button></form></div>
<div class='card'><h2>Your Contracts</h2><table><tr><th>Player</th><th>Position</th><th>Start</th><th>End</th><th>Length</th><th>Fee</th><th>Status</th><th></th></tr>{% for r in mine %}<tr><td>{{r.player}}</td><td>{{r.position}}</td><td>{{r.start_date}}</td><td>{{r.end_date}}</td><td>{{r.duration_months}}m</td><td>£{{'%.2f'|format(r.transfer_fee or 0)}}</td><td>{{r.status}}</td><td>{% if r.status=='active' %}<form method='post'><input type='hidden' name='action' value='release_contract'><input type='hidden' name='contract_id' value='{{r.id}}'><button class='danger'>Release</button></form>{% endif %}</td></tr>{% else %}<tr><td colspan='8'>No contracts yet.</td></tr>{% endfor %}</table></div><p><a href='/contracts'>View all PSL contracts</a> · <a href='/'>Back to PSL</a></p></div></body></html>""",team=team,mine=mine,free_agents=free_agents,message=message,error=error)

@app.route('/admin/contracts')
@admin_required
def admin_contracts():
    _contracts_table(); c=db()
    rows=c.execute("""SELECT co.*,p.name player,t.name team FROM contracts co JOIN players p ON p.id=co.player_id JOIN teams t ON t.id=co.team_id ORDER BY co.id DESC""").fetchall(); c.close()
    return render_template_string("""<!doctype html><html><head><meta charset='utf-8'><title>Admin Contracts</title><style>body{font-family:Arial;background:#111;color:#eee;padding:25px}.wrap{max-width:1200px;margin:auto}.card{background:#1b1b1b;border:1px solid #333;border-radius:14px;padding:20px}table{width:100%;border-collapse:collapse}th,td{padding:10px;border-bottom:1px solid #333;text-align:left}a{color:#7dd3fc}</style></head><body><div class='wrap'><h1>PSL Contract Administration</h1><div class='card'><table><tr><th>ID</th><th>Player</th><th>Team</th><th>Start</th><th>End</th><th>Length</th><th>Fee</th><th>Status</th></tr>{% for r in rows %}<tr><td>{{r.id}}</td><td>{{r.player}}</td><td>{{r.team}}</td><td>{{r.start_date}}</td><td>{{r.end_date}}</td><td>{{r.duration_months}}m</td><td>£{{'%.2f'|format(r.transfer_fee or 0)}}</td><td>{{r.status}}</td></tr>{% else %}<tr><td colspan='8'>No contracts yet.</td></tr>{% endfor %}</table></div><p><a href='/admin'>Back to admin</a></p></div></body></html>""",rows=rows)
# ===== END PSL_CONTRACTS_PATCH_V1 =====

# Add-on routes use the existing Flask app and database; schema changes are additive.
from psl_features import register_features
register_features(app, db, standings)

if __name__=="__main__":
    init_db()
    app.run(debug=True)
