from pathlib import Path
APP=Path('app.py')
if not APP.exists(): raise SystemExit('app.py not found. Run from PSL_Website_v2.')
src=APP.read_text(encoding='utf-8')
if 'PSL_CONTRACTS_PATCH_V1' in src:
    print('Contracts patch is already installed.'); raise SystemExit
backup=APP.with_name('app_before_contracts_patch.py')
if not backup.exists(): backup.write_text(src,encoding='utf-8')
if 'render_template_string' not in src:
    src=src.replace('from flask import Flask, render_template, request, redirect, url_for, session, jsonify, abort','from flask import Flask, render_template, render_template_string, request, redirect, url_for, session, jsonify, abort')
if 'from datetime import date' not in src:
    src=src.replace('from pathlib import Path\n','from pathlib import Path\nfrom datetime import date\n')

block = '''
# ===== PSL_CONTRACTS_PATCH_V1 =====
def _contracts_table():
    c=db()
    if os.getenv("DATABASE_URL"):
        c.execute("""CREATE TABLE IF NOT EXISTS contracts (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          player_id BIGINT NOT NULL, team_id BIGINT NOT NULL,
          start_date DATE NOT NULL, end_date DATE NOT NULL,
          duration_months INTEGER NOT NULL DEFAULT 1, transfer_fee REAL DEFAULT 0,
          status TEXT NOT NULL DEFAULT 'active', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
          released_at DATE, FOREIGN KEY(player_id) REFERENCES players(id) ON DELETE CASCADE,
          FOREIGN KEY(team_id) REFERENCES teams(id) ON DELETE CASCADE)""")
    else:
        c.execute("""CREATE TABLE IF NOT EXISTS contracts (
          id INTEGER PRIMARY KEY AUTOINCREMENT,
          player_id INTEGER NOT NULL, team_id INTEGER NOT NULL,
          start_date TEXT NOT NULL, end_date TEXT NOT NULL,
          duration_months INTEGER NOT NULL DEFAULT 1, transfer_fee REAL DEFAULT 0,
          status TEXT NOT NULL DEFAULT 'active', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
          released_at TEXT, FOREIGN KEY(player_id) REFERENCES players(id) ON DELETE CASCADE,
          FOREIGN KEY(team_id) REFERENCES teams(id) ON DELETE CASCADE)""")
    c.commit(); c.close()

def _contract_add_months(d, months):
    import calendar
    y=d.year+(d.month-1+months)//12; m=(d.month-1+months)%12+1
    return date(y,m,min(d.day,calendar.monthrange(y,m)[1]))

_contracts_table()

@app.route('/contracts')
def contracts_public():
    _contracts_table(); c=db()
    rows=c.execute("""SELECT co.*,p.name player,p.position,t.name team FROM contracts co
        JOIN players p ON p.id=co.player_id JOIN teams t ON t.id=co.team_id
        ORDER BY co.end_date ASC,p.name ASC""").fetchall(); c.close()
    return render_template_string("""
<!doctype html><html><head><meta charset='utf-8'><title>PSL Contracts</title>
<style>body{font-family:Arial;background:#111;color:#eee;padding:30px}.wrap{max-width:1100px;margin:auto}.card{background:#1b1b1b;border:1px solid #333;border-radius:14px;padding:18px;overflow:auto}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:11px;border-bottom:1px solid #333}th{color:#aaa}a{color:#7dd3fc}.active{color:#86efac}.expired{color:#fbbf24}.released{color:#f87171}</style></head>
<body><div class='wrap'><h1>PSL Contracts</h1><p>Player contracts, terms and status.</p><div class='card'><table><tr><th>Player</th><th>Team</th><th>Position</th><th>Start</th><th>End</th><th>Length</th><th>Fee</th><th>Status</th></tr>
{% for r in rows %}<tr><td>{{r.player}}</td><td>{{r.team}}</td><td>{{r.position}}</td><td>{{r.start_date}}</td><td>{{r.end_date}}</td><td>{{r.duration_months}}m</td><td>£{{'%.2f'|format(r.transfer_fee or 0)}}</td><td>{{r.status|upper}}</td></tr>{% else %}<tr><td colspan='8'>No contracts yet.</td></tr>{% endfor %}</table></div><p><a href='/'>Back to PSL</a></p></div></body></html>""",rows=rows)

@app.route('/manager/contracts',methods=['GET','POST'])
@manager_required
def manager_contracts(team):
    _contracts_table(); c=db(); message=None; error=None
    if request.method=='POST':
        action=request.form.get('action')
        try:
            if action=='sign_contract':
                player_id=int(request.form.get('player_id','0')); months=int(request.form.get('duration_months','1'))
                if months not in (1,3,6,12): raise ValueError('Contract length must be 1, 3, 6 or 12 months.')
                fee=float(request.form.get('transfer_fee','0') or 0)
                if fee<0: raise ValueError('Transfer fee cannot be negative.')
                p=c.execute('SELECT * FROM players WHERE id=?',(player_id,)).fetchone()
                if not p: raise ValueError('Player not found.')
                if p['team_id'] is not None: raise ValueError('That player is already signed to a team.')
                start=date.today(); end=_contract_add_months(start,months)
                c.execute("""INSERT INTO contracts(player_id,team_id,start_date,end_date,duration_months,transfer_fee,status)
                    VALUES(?,?,?,?,?,?,?)""",(player_id,team['id'],start.isoformat(),end.isoformat(),months,fee,'active'))
                c.execute('UPDATE players SET team_id=? WHERE id=?',(team['id'],player_id))
                c.execute("INSERT INTO transfers(player_id,from_team,to_team) VALUES(?,?,?)",(player_id,'Free Agent',team['name']))
                c.commit(); message=f"{p['name']} signed by {team['name']} until {end.isoformat()}."
            elif action=='release_contract':
                contract_id=int(request.form.get('contract_id','0'))
                r=c.execute("""SELECT co.*,p.name player FROM contracts co JOIN players p ON p.id=co.player_id
                    WHERE co.id=? AND co.team_id=? AND co.status='active'""",(contract_id,team['id'])).fetchone()
                if not r: raise ValueError('Active contract not found.')
                today=date.today().isoformat()
                c.execute("UPDATE contracts SET status='released',released_at=?,end_date=? WHERE id=?",(today,today,contract_id))
                c.execute('UPDATE players SET team_id=NULL WHERE id=? AND team_id=?',(r['player_id'],team['id']))
                c.execute("INSERT INTO transfers(player_id,from_team,to_team) VALUES(?,?,?)",(r['player_id'],team['name'],'Free Agent'))
                c.commit(); message=f"{r['player']} has been released and is now a Free Agent."
        except Exception as e:
            c.rollback(); error=str(e)
    mine=c.execute("""SELECT co.*,p.name player,p.position FROM contracts co JOIN players p ON p.id=co.player_id
        WHERE co.team_id=? ORDER BY co.end_date ASC""",(team['id'],)).fetchall()
    free_agents=c.execute('SELECT * FROM players WHERE team_id IS NULL ORDER BY position,name').fetchall(); c.close()
    return render_template_string("""
<!doctype html><html><head><meta charset='utf-8'><title>Team Contracts</title><style>
body{font-family:Arial;background:#111;color:#eee;padding:25px}.wrap{max-width:1100px;margin:auto}.card{background:#1b1b1b;border:1px solid #333;border-radius:14px;padding:20px;margin:15px 0}input,select{padding:10px;margin:5px;background:#222;color:#fff;border:1px solid #555;border-radius:7px}button{padding:10px 15px;background:#2563eb;color:#fff;border:0;border-radius:7px;cursor:pointer}.danger{background:#dc2626}.ok{background:#14532d;padding:12px;border-radius:8px}.err{background:#7f1d1d;padding:12px;border-radius:8px}table{width:100%;border-collapse:collapse}th,td{padding:10px;border-bottom:1px solid #333;text-align:left}a{color:#7dd3fc}</style></head>
<body><div class='wrap'><h1>{{team.name}} — Contracts</h1>{% if message %}<div class='ok'>{{message}}</div>{% endif %}{% if error %}<div class='err'>{{error}}</div>{% endif %}
<div class='card'><h2>Sign Free Agent</h2><form method='post'><input type='hidden' name='action' value='sign_contract'><select name='player_id' required>{% for p in free_agents %}<option value='{{p.id}}'>{{p.name}}{% if p.position %} — {{p.position}}{% endif %}</option>{% else %}<option>No free agents available</option>{% endfor %}</select><select name='duration_months'><option value='1'>1 month</option><option value='3'>3 months</option><option value='6'>6 months</option><option value='12'>12 months</option></select><input name='transfer_fee' type='number' step='0.01' min='0' value='0' placeholder='Transfer fee (£)'><button>Sign Player</button></form></div>
<div class='card'><h2>Your Contracts</h2><table><tr><th>Player</th><th>Position</th><th>Start</th><th>End</th><th>Length</th><th>Fee</th><th>Status</th><th></th></tr>{% for r in mine %}<tr><td>{{r.player}}</td><td>{{r.position}}</td><td>{{r.start_date}}</td><td>{{r.end_date}}</td><td>{{r.duration_months}}m</td><td>£{{'%.2f'|format(r.transfer_fee or 0)}}</td><td>{{r.status}}</td><td>{% if r.status=='active' %}<form method='post'><input type='hidden' name='action' value='release_contract'><input type='hidden' name='contract_id' value='{{r.id}}'><button class='danger'>Release</button></form>{% endif %}</td></tr>{% else %}<tr><td colspan='8'>No contracts yet.</td></tr>{% endfor %}</table></div><p><a href='/contracts'>View all PSL contracts</a> · <a href='/'>Back to PSL</a></p></div></body></html>""",team=team,mine=mine,free_agents=free_agents,message=message,error=error)

@app.route('/admin/contracts')
@admin_required
def admin_contracts():
    _contracts_table(); c=db()
    rows=c.execute("""SELECT co.*,p.name player,t.name team FROM contracts co JOIN players p ON p.id=co.player_id JOIN teams t ON t.id=co.team_id ORDER BY co.id DESC""").fetchall(); c.close()
    return render_template_string("""<!doctype html><html><head><meta charset='utf-8'><title>Admin Contracts</title><style>body{font-family:Arial;background:#111;color:#eee;padding:25px}.wrap{max-width:1200px;margin:auto}.card{background:#1b1b1b;border:1px solid #333;border-radius:14px;padding:20px}table{width:100%;border-collapse:collapse}th,td{padding:10px;border-bottom:1px solid #333;text-align:left}a{color:#7dd3fc}</style></head><body><div class='wrap'><h1>PSL Contract Administration</h1><div class='card'><table><tr><th>ID</th><th>Player</th><th>Team</th><th>Start</th><th>End</th><th>Length</th><th>Fee</th><th>Status</th></tr>{% for r in rows %}<tr><td>{{r.id}}</td><td>{{r.player}}</td><td>{{r.team}}</td><td>{{r.start_date}}</td><td>{{r.end_date}}</td><td>{{r.duration_months}}m</td><td>£{{'%.2f'|format(r.transfer_fee or 0)}}</td><td>{{r.status}}</td></tr>{% else %}<tr><td colspan='8'>No contracts yet.</td></tr>{% endfor %}</table></div><p><a href='/admin'>Back to admin</a></p></div></body></html>""",rows=rows)
# ===== END PSL_CONTRACTS_PATCH_V1 =====
'''
marker='\nif __name__=="__main__":'
if marker not in src: marker='\nif __name__ == "__main__":'
if marker not in src: raise SystemExit('Could not find Flask startup block; no changes made.')
src=src.replace(marker,block+marker,1)
APP.write_text(src,encoding='utf-8')
print('SUCCESS: Contract system added to app.py')
print('Backup:',backup.name)
print('Routes: /contracts  /manager/contracts  /admin/contracts')
