"""PSL Career Mode, Transfer Market, Club Management and Match Centre add-ons.
This module is registered by app.py and uses the existing database via db().
All schema changes are additive to preserve existing PSL records.
"""
import os
from datetime import date
from functools import wraps
from flask import render_template, request, redirect, url_for, session, flash, abort, jsonify

def register_features(app, db, standings):
    def ensure_tables():
        c = db()
        pg = bool(os.getenv("DATABASE_URL"))
        if pg:
            statements = [
                """CREATE TABLE IF NOT EXISTS player_match_stats (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    player_id BIGINT NOT NULL REFERENCES players(id) ON DELETE CASCADE,
                    fixture_id BIGINT REFERENCES fixtures(id) ON DELETE SET NULL,
                    appearances INTEGER NOT NULL DEFAULT 1,
                    goals INTEGER NOT NULL DEFAULT 0,
                    assists INTEGER NOT NULL DEFAULT 0,
                    rating REAL,
                    notes TEXT DEFAULT '',
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    UNIQUE(player_id, fixture_id))""",
                """CREATE TABLE IF NOT EXISTS club_finances (
                    team_id BIGINT PRIMARY KEY REFERENCES teams(id) ON DELETE CASCADE,
                    transfer_budget REAL NOT NULL DEFAULT 0,
                    wage_budget REAL NOT NULL DEFAULT 0,
                    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)""",
                """CREATE TABLE IF NOT EXISTS transfer_requests (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    player_id BIGINT NOT NULL REFERENCES players(id) ON DELETE CASCADE,
                    from_team_id BIGINT REFERENCES teams(id) ON DELETE SET NULL,
                    to_team_id BIGINT NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
                    requested_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
                    fee REAL NOT NULL DEFAULT 0,
                    status TEXT NOT NULL DEFAULT 'pending',
                    note TEXT DEFAULT '',
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    resolved_at TIMESTAMP)""",
                """CREATE TABLE IF NOT EXISTS contracts (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    player_id BIGINT NOT NULL REFERENCES players(id) ON DELETE CASCADE,
                    team_id BIGINT NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
                    start_date TEXT NOT NULL, end_date TEXT NOT NULL,
                    duration_months INTEGER NOT NULL DEFAULT 1, transfer_fee REAL DEFAULT 0,
                    status TEXT NOT NULL DEFAULT 'active', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    released_at TEXT)""",
                """CREATE TABLE IF NOT EXISTS contract_offers (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    player_id BIGINT NOT NULL REFERENCES players(id) ON DELETE CASCADE,
                    team_id BIGINT NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
                    start_date TEXT NOT NULL, end_date TEXT NOT NULL,
                    duration_months INTEGER NOT NULL, fee REAL DEFAULT 0,
                    status TEXT NOT NULL DEFAULT 'pending',
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    responded_at TIMESTAMP,
                    offered_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL)"""
            ]
        else:
            statements = [
                """CREATE TABLE IF NOT EXISTS player_match_stats (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    player_id INTEGER NOT NULL REFERENCES players(id) ON DELETE CASCADE,
                    fixture_id INTEGER REFERENCES fixtures(id) ON DELETE SET NULL,
                    appearances INTEGER NOT NULL DEFAULT 1,
                    goals INTEGER NOT NULL DEFAULT 0,
                    assists INTEGER NOT NULL DEFAULT 0,
                    rating REAL,
                    notes TEXT DEFAULT '',
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    UNIQUE(player_id, fixture_id))""",
                """CREATE TABLE IF NOT EXISTS club_finances (
                    team_id INTEGER PRIMARY KEY REFERENCES teams(id) ON DELETE CASCADE,
                    transfer_budget REAL NOT NULL DEFAULT 0,
                    wage_budget REAL NOT NULL DEFAULT 0,
                    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)""",
                """CREATE TABLE IF NOT EXISTS transfer_requests (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    player_id INTEGER NOT NULL REFERENCES players(id) ON DELETE CASCADE,
                    from_team_id INTEGER REFERENCES teams(id) ON DELETE SET NULL,
                    to_team_id INTEGER NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
                    requested_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
                    fee REAL NOT NULL DEFAULT 0,
                    status TEXT NOT NULL DEFAULT 'pending',
                    note TEXT DEFAULT '',
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    resolved_at TIMESTAMP)""",
                """CREATE TABLE IF NOT EXISTS contracts (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    player_id INTEGER NOT NULL REFERENCES players(id) ON DELETE CASCADE,
                    team_id INTEGER NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
                    start_date TEXT NOT NULL, end_date TEXT NOT NULL,
                    duration_months INTEGER NOT NULL DEFAULT 1, transfer_fee REAL DEFAULT 0,
                    status TEXT NOT NULL DEFAULT 'active', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    released_at TEXT)""",
                """CREATE TABLE IF NOT EXISTS contract_offers (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    player_id INTEGER NOT NULL REFERENCES players(id) ON DELETE CASCADE,
                    team_id INTEGER NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
                    start_date TEXT NOT NULL, end_date TEXT NOT NULL,
                    duration_months INTEGER NOT NULL, fee REAL DEFAULT 0,
                    status TEXT NOT NULL DEFAULT 'pending',
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    responded_at TIMESTAMP,
                    offered_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL)"""
            ]
        for sql in statements:
            c.execute(sql)
        c.commit()
        c.close()

    def current_user():
        uid = session.get("user_id")
        if not uid:
            return None
        c = db()
        row = c.execute("SELECT * FROM users WHERE id=?", (uid,)).fetchone()
        c.close()
        return row

    def manager_team():
        user = current_user()
        discord_id = session.get("discord_id")
        c = db()
        team = None
        if user:
            if user["team_id"]:
                team = c.execute("SELECT * FROM teams WHERE id=?", (user["team_id"],)).fetchone()
            if not team and user["username"]:
                team = c.execute("SELECT * FROM teams WHERE lower(trim(manager))=lower(trim(?)) LIMIT 1",
                                 (user["username"],)).fetchone()
        if not team and discord_id:
            team = c.execute("SELECT * FROM teams WHERE discord_id=?", (discord_id,)).fetchone()
        c.close()
        return user, team

    def admin_user():
        return bool(session.get("admin") or session.get("is_admin"))

    def login_required():
        return redirect(url_for("login", next=request.path))

    def add_months(start, months):
        import calendar
        y = start.year + (start.month - 1 + months) // 12
        m = (start.month - 1 + months) % 12 + 1
        return date(y, m, min(start.day, calendar.monthrange(y, m)[1]))

    ensure_tables()

    @app.get("/career")
    def career_index():
        c = db()
        rows = c.execute("""SELECT p.id,p.name,p.position,COALESCE(t.name,'Free Agent') team,
                p.appearances,p.goals,p.assists,
                CASE WHEN p.appearances>0 THEN ROUND(1.0*p.goals/p.appearances,2) ELSE 0 END goals_per_app
            FROM players p LEFT JOIN teams t ON t.id=p.team_id
            ORDER BY p.goals DESC,p.assists DESC,p.appearances DESC,p.name""").fetchall()
        c.close()
        return render_template("career.html", players=rows)

    @app.get("/career/<int:player_id>")
    def career_player(player_id):
        c = db()
        player = c.execute("""SELECT p.*,COALESCE(t.name,'Free Agent') team
            FROM players p LEFT JOIN teams t ON t.id=p.team_id WHERE p.id=?""", (player_id,)).fetchone()
        if not player:
            c.close()
            abort(404)
        matches = c.execute("""SELECT s.*,f.scheduled,f.round_no,h.name home,a.name away,
                f.home_score,f.away_score,f.status
            FROM player_match_stats s LEFT JOIN fixtures f ON f.id=s.fixture_id
            LEFT JOIN teams h ON h.id=f.home_id LEFT JOIN teams a ON a.id=f.away_id
            WHERE s.player_id=? ORDER BY s.id DESC LIMIT 50""", (player_id,)).fetchall()
        transfers = c.execute("SELECT * FROM transfers WHERE player_id=? ORDER BY id DESC", (player_id,)).fetchall()
        contracts = c.execute("""SELECT co.*,t.name team FROM contracts co JOIN teams t ON t.id=co.team_id
            WHERE co.player_id=? ORDER BY co.id DESC""", (player_id,)).fetchall()
        season = c.execute("""SELECT COALESCE(SUM(appearances),0) apps,COALESCE(SUM(goals),0) goals,
                COALESCE(SUM(assists),0) assists,ROUND(AVG(rating),2) avg_rating
            FROM player_match_stats WHERE player_id=?""", (player_id,)).fetchone()
        c.close()
        return render_template("career_player.html", player=player, matches=matches,
                               transfers=transfers, contracts=contracts, season=season)

    @app.route("/transfer-market", methods=["GET", "POST"])
    def transfer_market():
        ensure_tables()
        user, team = manager_team()
        message = request.args.get("message", "")
        error = ""
        if request.method == "POST":
            if not user and not session.get("discord_id"):
                return login_required()
            if not team:
                return "Your account is not linked to a PSL club. Ask an admin to link your account to a team.", 403
            try:
                player_id = int(request.form.get("player_id", "0"))
                months = int(request.form.get("duration_months", "3"))
                fee = float(request.form.get("fee", "0") or 0)
                start_text = request.form.get("start_date") or date.today().isoformat()
                start = date.fromisoformat(start_text)
                if months not in (1, 3, 6, 12):
                    raise ValueError("Choose a contract length of 1, 3, 6 or 12 months.")
                if fee < 0:
                    raise ValueError("Fee cannot be negative.")
                c = db()
                player = c.execute("SELECT * FROM players WHERE id=? AND team_id IS NULL", (player_id,)).fetchone()
                if not player:
                    c.close()
                    raise ValueError("That player is no longer available as a free agent.")
                if os.getenv("DATABASE_URL"):
                    c.execute("""INSERT INTO contract_offers
                        (player_id,team_id,start_date,end_date,duration_months,fee,status,offered_by_user_id)
                        VALUES(?,?,?,?,?,?,'pending',?)""",
                        (player_id, team["id"], start.isoformat(), add_months(start, months).isoformat(),
                         months, fee, user["id"] if user else None))
                else:
                    c.execute("""INSERT INTO contract_offers
                        (player_id,team_id,start_date,end_date,duration_months,fee,status,offered_by_user_id)
                        VALUES(?,?,?,?,?,?,'pending',?)""",
                        (player_id, team["id"], start.isoformat(), add_months(start, months).isoformat(),
                         months, fee, user["id"] if user else None))
                c.commit()
                c.close()
                return redirect(url_for("transfer_market", message=f"Contract offer sent for {player['name']}."))
            except Exception as exc:
                error = str(exc)
        c = db()
        free_agents = c.execute("""SELECT p.*,COALESCE(t.name,'Free Agent') team FROM players p
            LEFT JOIN teams t ON t.id=p.team_id WHERE p.team_id IS NULL ORDER BY p.position,p.name""").fetchall()
        latest = c.execute("""SELECT tr.*,p.name player FROM transfers tr JOIN players p ON p.id=tr.player_id
            ORDER BY tr.id DESC LIMIT 12""").fetchall()
        offers = []
        if team:
            offers = c.execute("""SELECT o.*,p.name player FROM contract_offers o JOIN players p ON p.id=o.player_id
                WHERE o.team_id=? ORDER BY o.id DESC LIMIT 10""", (team["id"],)).fetchall()
        c.close()
        return render_template("transfer_market.html", team=team, free_agents=free_agents,
                               latest=latest, offers=offers, message=message, error=error, today=date.today().isoformat())

    @app.route("/manager/contracts/offers", methods=["GET", "POST"])
    def manager_contract_offers():
        if admin_user():
            return redirect(url_for("admin_contract_offers"))
        return redirect(url_for("transfer_market"))

    @app.route("/contract-offers", methods=["GET"])
    def player_contract_offers():
        user = current_user()
        if not user:
            return login_required()
        if not user["player_id"]:
            return render_template("message.html", title="Contract offers",
                message="Your website account is not linked to a player profile yet. Ask an admin to link it.")
        c = db()
        offers = c.execute("""SELECT o.*,t.name team_name,p.name player_name FROM contract_offers o
            JOIN teams t ON t.id=o.team_id JOIN players p ON p.id=o.player_id
            WHERE o.player_id=? AND o.status='pending' ORDER BY o.created_at DESC""", (user["player_id"],)).fetchall()
        c.close()
        return render_template("contract_offers.html", offers=offers)

    @app.post("/contract-offers/<int:offer_id>/reject")
    def reject_contract_offer(offer_id):
        user = current_user()
        if not user or not user["player_id"]:
            return login_required()
        c = db()
        changed = c.execute("""UPDATE contract_offers SET status='rejected',responded_at=CURRENT_TIMESTAMP
            WHERE id=? AND player_id=? AND status='pending'""", (offer_id, user["player_id"]))
        c.commit()
        c.close()
        return redirect(url_for("player_contract_offers"))

    @app.post("/contract-offers/<int:offer_id>/accept")
    def accept_contract_offer(offer_id):
        user = current_user()
        if not user or not user["player_id"]:
            return login_required()
        c = db()
        try:
            if not os.getenv("DATABASE_URL"):
                c.execute("BEGIN IMMEDIATE")
            offer = c.execute("""SELECT o.*,p.team_id player_team_id,p.name player_name,t.name team_name
                FROM contract_offers o JOIN players p ON p.id=o.player_id JOIN teams t ON t.id=o.team_id
                WHERE o.id=? AND o.player_id=? AND o.status='pending'""",
                (offer_id, user["player_id"])).fetchone()
            if not offer:
                raise ValueError("Offer not found or already answered.")
            if offer["player_team_id"] is not None:
                raise ValueError("Your player is already signed to a club.")
            active = c.execute("SELECT id FROM contracts WHERE player_id=? AND status='active' LIMIT 1",
                                (offer["player_id"],)).fetchone()
            if active:
                raise ValueError("An active contract already exists for this player.")
            # Existing contract table uses transfer_fee. Preserve its schema.
            c.execute("""INSERT INTO contracts(player_id,team_id,start_date,end_date,duration_months,transfer_fee,status)
                VALUES(?,?,?,?,?,?, 'active')""",
                (offer["player_id"], offer["team_id"], offer["start_date"], offer["end_date"],
                 offer["duration_months"], offer["fee"] or 0))
            c.execute("UPDATE players SET team_id=? WHERE id=?", (offer["team_id"], offer["player_id"]))
            c.execute("INSERT INTO transfers(player_id,from_team,to_team) VALUES(?,?,?)",
                       (offer["player_id"], "Free Agent", offer["team_name"]))
            c.execute("UPDATE contract_offers SET status='accepted',responded_at=CURRENT_TIMESTAMP WHERE id=?",
                      (offer_id,))
            c.execute("""UPDATE contract_offers SET status='rejected',responded_at=CURRENT_TIMESTAMP
                WHERE player_id=? AND status='pending' AND id<>?""", (offer["player_id"], offer_id))
            c.commit()
        except Exception as exc:
            c.rollback()
            c.close()
            return render_template("message.html", title="Could not accept offer", message=str(exc)), 400
        c.close()
        return redirect(url_for("career_player", player_id=user["player_id"]))

    @app.route("/admin/contracts/offers", methods=["GET", "POST"])
    def admin_contract_offers():
        if not admin_user():
            return login_required()
        c = db()
        if request.method == "POST":
            action = request.form.get("action")
            try:
                if action == "reject":
                    c.execute("UPDATE contract_offers SET status='rejected',responded_at=CURRENT_TIMESTAMP WHERE id=? AND status='pending'",
                              (int(request.form.get("offer_id", "0")),))
                elif action == "cancel":
                    c.execute("UPDATE contract_offers SET status='cancelled',responded_at=CURRENT_TIMESTAMP WHERE id=? AND status='pending'",
                              (int(request.form.get("offer_id", "0")),))
                c.commit()
            except Exception:
                c.rollback()
        rows = c.execute("""SELECT o.*,p.name player,t.name team FROM contract_offers o
            JOIN players p ON p.id=o.player_id JOIN teams t ON t.id=o.team_id ORDER BY o.id DESC LIMIT 200""").fetchall()
        c.close()
        return render_template("admin_offers.html", offers=rows)

    @app.route("/club-management", methods=["GET", "POST"])
    def club_management():
        ensure_tables()
        user, team = manager_team()
        if not admin_user() and not team:
            if not user and not session.get("discord_id"):
                return login_required()
            return "Your account is not linked to a PSL club.", 403
        c = db()
        if request.method == "POST":
            if not admin_user():
                c.close()
                return "Only a PSL administrator can edit club budgets.", 403
            try:
                team_id = int(request.form.get("team_id", "0"))
                budget = float(request.form.get("transfer_budget", "0") or 0)
                wages = float(request.form.get("wage_budget", "0") or 0)
                if budget < 0 or wages < 0:
                    raise ValueError("Budgets cannot be negative.")
                exists = c.execute("SELECT id FROM teams WHERE id=?", (team_id,)).fetchone()
                if not exists:
                    raise ValueError("Club not found.")
                if os.getenv("DATABASE_URL"):
                    c.execute("""INSERT INTO club_finances(team_id,transfer_budget,wage_budget,updated_at)
                        VALUES(?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(team_id) DO UPDATE SET
                        transfer_budget=EXCLUDED.transfer_budget,wage_budget=EXCLUDED.wage_budget,updated_at=CURRENT_TIMESTAMP""",
                        (team_id, budget, wages))
                else:
                    c.execute("""INSERT INTO club_finances(team_id,transfer_budget,wage_budget,updated_at)
                        VALUES(?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(team_id) DO UPDATE SET
                        transfer_budget=excluded.transfer_budget,wage_budget=excluded.wage_budget,updated_at=CURRENT_TIMESTAMP""",
                        (team_id, budget, wages))
                c.commit()
            except Exception:
                c.rollback()
        if admin_user():
            teams = c.execute("""SELECT t.*,COALESCE(f.transfer_budget,0) transfer_budget,
                    COALESCE(f.wage_budget,0) wage_budget FROM teams t LEFT JOIN club_finances f ON f.team_id=t.id
                    ORDER BY t.name""").fetchall()
            selected = team
        else:
            teams = c.execute("""SELECT t.*,COALESCE(f.transfer_budget,0) transfer_budget,
                    COALESCE(f.wage_budget,0) wage_budget FROM teams t LEFT JOIN club_finances f ON f.team_id=t.id
                    WHERE t.id=?""", (team["id"],)).fetchall()
            selected = team
        if selected:
            squad = c.execute("SELECT * FROM players WHERE team_id=? ORDER BY position,name", (selected["id"],)).fetchall()
            fixtures = c.execute("""SELECT f.*,h.name home,a.name away FROM fixtures f
                JOIN teams h ON h.id=f.home_id JOIN teams a ON a.id=f.away_id
                WHERE (f.home_id=? OR f.away_id=?) ORDER BY CASE WHEN f.status='scheduled' THEN 0 ELSE 1 END,
                f.scheduled,f.id LIMIT 12""", (selected["id"], selected["id"])).fetchall()
        else:
            squad, fixtures = [], []
        c.close()
        return render_template("club_management.html", teams=teams, selected=selected, squad=squad,
                               fixtures=fixtures, is_admin=admin_user())

    @app.route("/match-centre", methods=["GET", "POST"])
    def match_centre():
        if request.method == "POST":
            if not admin_user():
                return login_required()
            try:
                fixture_id = int(request.form.get("fixture_id", "0"))
                hs = int(request.form.get("home_score", "-1"))
                aws = int(request.form.get("away_score", "-1"))
                if hs < 0 or aws < 0:
                    raise ValueError("Scores must be zero or higher.")
                c = db()
                fixture = c.execute("SELECT * FROM fixtures WHERE id=?", (fixture_id,)).fetchone()
                if not fixture:
                    c.close()
                    abort(404)
                c.execute("UPDATE fixtures SET status='played',home_score=?,away_score=? WHERE id=?",
                          (hs, aws, fixture_id))
                c.commit()
                c.close()
                return redirect(url_for("match_centre", message="Result saved"))
            except ValueError as exc:
                return render_template("message.html", title="Invalid result", message=str(exc)), 400
        c = db()
        rows = c.execute("""SELECT f.*,h.name home,a.name away FROM fixtures f
            JOIN teams h ON h.id=f.home_id JOIN teams a ON a.id=f.away_id
            ORDER BY CASE WHEN f.status='scheduled' THEN 0 ELSE 1 END,
            COALESCE(f.scheduled,''),COALESCE(f.round_no,999999),f.id""").fetchall()
        c.close()
        return render_template("match_centre.html", fixtures=rows, table=standings(),
                               is_admin=admin_user(), message=request.args.get("message", ""))

    @app.route("/admin/career-stats", methods=["GET", "POST"])
    def admin_career_stats():
        if not admin_user():
            return login_required()
        c = db()
        message = ""
        error = ""
        if request.method == "POST":
            try:
                player_id = int(request.form.get("player_id", "0"))
                fixture_raw = request.form.get("fixture_id", "").strip()
                fixture_id = int(fixture_raw) if fixture_raw else None
                appearances = int(request.form.get("appearances", "1"))
                goals = int(request.form.get("goals", "0"))
                assists = int(request.form.get("assists", "0"))
                rating_raw = request.form.get("rating", "").strip()
                rating = float(rating_raw) if rating_raw else None
                if min(appearances, goals, assists) < 0:
                    raise ValueError("Appearances, goals and assists cannot be negative.")
                if rating is not None and not (0 <= rating <= 10):
                    raise ValueError("Rating must be between 0 and 10.")
                p = c.execute("SELECT * FROM players WHERE id=?", (player_id,)).fetchone()
                if not p:
                    raise ValueError("Player not found.")
                if fixture_id and not c.execute("SELECT id FROM fixtures WHERE id=?", (fixture_id,)).fetchone():
                    raise ValueError("Fixture not found.")
                previous = None
                if fixture_id is not None:
                    previous = c.execute("SELECT appearances,goals,assists FROM player_match_stats WHERE player_id=? AND fixture_id=?",
                                         (player_id, fixture_id)).fetchone()
                if os.getenv("DATABASE_URL"):
                    c.execute("""INSERT INTO player_match_stats(player_id,fixture_id,appearances,goals,assists,rating,notes)
                        VALUES(?,?,?,?,?,?,?) ON CONFLICT(player_id,fixture_id) DO UPDATE SET
                        appearances=EXCLUDED.appearances,goals=EXCLUDED.goals,assists=EXCLUDED.assists,
                        rating=EXCLUDED.rating,notes=EXCLUDED.notes""",
                        (player_id, fixture_id, appearances, goals, assists, rating, request.form.get("notes","").strip()))
                else:
                    c.execute("""INSERT INTO player_match_stats(player_id,fixture_id,appearances,goals,assists,rating,notes)
                        VALUES(?,?,?,?,?,?,?) ON CONFLICT(player_id,fixture_id) DO UPDATE SET
                        appearances=excluded.appearances,goals=excluded.goals,assists=excluded.assists,
                        rating=excluded.rating,notes=excluded.notes""",
                        (player_id, fixture_id, appearances, goals, assists, rating, request.form.get("notes","").strip()))
                # Preserve pre-existing totals. When editing a fixture entry, only apply the delta.
                # Query again after the upsert so the stored row is authoritative.
                if fixture_id is not None:
                    stored = c.execute("SELECT appearances,goals,assists FROM player_match_stats WHERE player_id=? AND fixture_id=?",
                                       (player_id, fixture_id)).fetchone()
                    # Existing data was read after upsert above in older versions; use current row totals safely.
                    # Apply a delta only if an earlier entry existed before this request.
                    if previous:
                        delta = (appearances - previous["appearances"], goals - previous["goals"], assists - previous["assists"])
                    else:
                        delta = (appearances, goals, assists)
                else:
                    delta = (appearances, goals, assists)
                c.execute("UPDATE players SET appearances=COALESCE(appearances,0)+?,goals=COALESCE(goals,0)+?,assists=COALESCE(assists,0)+? WHERE id=?",
                          (delta[0], delta[1], delta[2], player_id))
                c.commit()
                message = "Player career stats saved."
            except Exception as exc:
                c.rollback()
                error = str(exc)
        players = c.execute("SELECT id,name,position FROM players ORDER BY name").fetchall()
        fixtures = c.execute("""SELECT f.id,f.scheduled,h.name home,a.name away FROM fixtures f
            JOIN teams h ON h.id=f.home_id JOIN teams a ON a.id=f.away_id ORDER BY f.id DESC LIMIT 100""").fetchall()
        recent = c.execute("""SELECT s.*,p.name player FROM player_match_stats s JOIN players p ON p.id=s.player_id
            ORDER BY s.id DESC LIMIT 50""").fetchall()
        c.close()
        return render_template("admin_career_stats.html", players=players, fixtures=fixtures,
                               recent=recent, message=message, error=error)

    @app.get("/api/discord/health")
    def discord_health():
        return jsonify(ok=True, service="PSL website sync", endpoints=["/api/results", "/api/discord/result"])

    # Alias for existing bot implementations and a documented, stable integration path.
    app.add_url_rule("/api/discord/result", endpoint="discord_result_alias",
                     view_func=app.view_functions["api_result"], methods=["POST"])
